POST http://localhost:7777/server/v1/users?name=하이하이
###
POST http://localhost:7777/server/v1/users?name=하이하이2
###
GET http://localhost:7777/server/v1/users

###
PUT http://localhost:7777/server/v1/users/1?name=사실 바이임
###
DELETE http://localhost:7777/server/v1/users/1